//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blessrng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reqest
    {
        public int ID { get; set; }
        public string First { get; set; }
        public string Second { get; set; }
        public string Third { get; set; }
        public string Phone { get; set; }
        public string Out { get; set; }
        public string In { get; set; }
        public Nullable<System.DateTime> Date_Out { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
